version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            - v1-dependencies-
      - run: cat /dev/null | sbt test:compile
      - save_cache:
          paths:
            - ~/.m2
          key: v1-dependencies--{{ checksum "build.sbt" }}
      - run: cat /dev/null | sbt test:test
  deploy:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    environment:
      JVM_OPTS: -Xmx3200m
      TERM: dumb
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "build.sbt" }}
            - v1-dependencies-
      - run: cat /dev/null | mkdir -p .gnupg
      - run: cat /dev/null | echo $GPG_SEC | base64 --decode > .gnupg/secring.asc
      - run: cat /dev/null | echo $GPG_PUB | base64 --decode > .gnupg/pubring.asc
      - run: cat /dev/null | sbt releaseEarly
workflows:
  version: 2
  build:
    jobs:
      - build
  release:
    jobs:
      - build:
          filters:
            tags:
              only: /^v[0-9.]+.*/
            branches:
              ignore: /.*/
      - deploy:
          requires:
            - build
          filters:
            tags:
              only: /^v[0-9.]+.*/
            branches:
              ignore: /.*/
